Create nodes for every single page and allow multiple page types
ButterCMS/buttercms-gridsome-plugin pull request #12
Opened 2021-08-17 19:19 UTC by orlyohreally

Trello card: https://trello.com/c/hST0DgFo/1246-update-plugin-to-be-able-to-query-multiple-single-pages

- allow querying all single pages without specifying their slugs in the plugin configurations
- allow querying multiple page types pages

2021-08-18 03:01 UTC, courcelan requested changes
This all looks good. I would update to check for a rejection in the main promise so that we can tell the user where the process failed. Otherwise looks straightforward.

On one note, per comment in Trello, there was mention that `pages` is depreciated. If thats the case, then we still need code in there to operate on `pages` being included in the options. Depreciation here means that the code still runs (perhaps in non-updated form), but the developer should move to the non-depreciated code. 

If we are not going to account for use of `pages` and that code has been removed, then we need to announce/consider that as a *Breaking Change* and the semvar versioning should be `2.0.0` as we are introducing said breaking change.

Thanks!

2021-08-18 03:01 UTC, courcelan commented on index.js
> +      ]);
good use of `Promise.all`, but there should be a try/catch or at least receive a `reject` result so we can inform user that one of the functions has an error.

2021-08-23 18:20 UTC, orlyohreally commented
@courcelan The PR is ready for review. I have really refactored the code and added some tests.

2021-08-27 15:42 UTC, courcelan requested changes
Wow to adding tests! Nice!

Overall looks great, lots of goodness here. Gave a few instances where updates would ensure code was cleaner to parse and a bit more performant depending on the data load.

Thanks!

2021-08-27 15:42 UTC, courcelan commented on Readme.md
> +1. If you’re a Gridsome/graphQL newbie like me, figuring out how to shape your GraphQL query is the hardest part of the journey. RTFM just a bit, specifically this doc on [Introspection](https://grap
Lets change `RTFM` to `RTM`, no need to be edgy with the additional curse word.

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +    if ((this.locales || []).length) {
is the `|| []` needed if we already ensure its existence in the constructor?

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +        (this.locales || []).map(locale =>
same here

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +        (this.locales || []).map(locale =>
if we are going to do this: `this.locales || []`, then lets assign to a local variable so we don't have to do it twice.

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +      allPosts.push(...data);
what is `data`? is it an array of values?

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +        allItems = (await Promise.all(
nice use of Promise.all

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +    return collectionsSlugs.reduce(async (resPromise, collectionSlug) => {
do we also need a promise all on the reduce? I believe it functions that `[].map` and async functions. Just checking to be sure.

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +    }
There's a lot of object-spread going on here. Since we don't know how much data is coming back from server (or how many keys an object may have), we can try and limit spread, which takes up time as its creating internal JS maps/variables each time.

- `params` only gets used once and theres no need to spread it, as it will ultimately just get spread again. 
- `locale` gets used twice, so we can check for it just once and it never changes after calling the function, so we can set it up as a local variable outside the `while`

```javascript
const localLocale = locale
    ? { locale }
    : {}
```

if `locale` doesn't exist, we assign an empty object, which "disappears" on spread as it has no key/values. We only need to check its validity once, and `...(locale && { locale })` is an odd construction for people to parse.

- `data`'s item array is needlessly spread into a push and we are spreading each item just to add a possible`locale`. We can refine that.

without a local `param` variable: 

```javascript
const localLocale = locale
    ? { locale }
    : {}

let page = 1;

while (page) {
    const pages = await this.client.page.list(
        pageType, 
        {
            ...this.params,
            ...localLocale,
            page
        }
    );
    
    const {
        data,
        meta: { next_page: nextPage }
    } = pages.data;
    
    data.forEach(
        item => {
            pagesWithPageType.push({
                ...item,
                ...localLocale
            })       
        }
    )
    
    page = nextPage;
}
```

If you want to keep the local `params` to be safe, we can still lessen spread:

```javascript
const params = { ...this.params }

if (locale) params.locale = locale

let page = 1;

while (page) {
    params.page = page    

    const pages = await this.client.page.list(
        pageType, 
        params
    );
    
    const {
        data,
        meta: { next_page: nextPage }
    } = pages.data;
    
    data.forEach(
        item => {
            if (params.locale) item.locale = params.locale

            pagesWithPageType.push(item)       
        }
    )

    page = nextPage;
}
```

2021-08-27 15:42 UTC, courcelan commented on fetch.js
> +      });
follow similar fashion to above about `locale` and params.

2021-08-27 15:42 UTC, courcelan commented on index.js
> +      }
nice!

2021-08-27 15:42 UTC, courcelan commented on index.js
> +    );
is there a need to spread here? `contentType.addNode(post) should work I think. Is there any reason to create a copy of `post` here?

2021-08-27 15:42 UTC, courcelan commented on index.js
> +    );
This seems a little murky. You are removing `fields` from `page` so that key/value doesn't get added to the node. Makes sense! But its really just a renaming of the key from `fields` to `data`, which is set up but then not used.

try this:

```javascript
pages.forEach(page => {
    // remove `fields` as a key from page so it doesn't get added to node
    // needs to be renamed to `data` for use
    const { 
        fields: data, 
        ...pageData 
    } = page;
    
    // create node
    // - by assigning `page_type` explicitly here, we overwrite `pageData.page_type`
    const node = {
        ...pageData,
        data,
        page_type: page.page_type || '*'
    };

    contentType.addNode(node);
});
```

2021-08-29 09:02 UTC, orlyohreally commented on fetch.js
> +      allPosts.push(...data);
Yes, an array of posts

2021-08-29 09:04 UTC, orlyohreally commented on fetch.js
> +    return collectionsSlugs.reduce(async (resPromise, collectionSlug) => {
What do you mean? Which line exactly are you talking about?

2021-09-02 19:26 UTC, courcelan requested changes
@orlyohreally Everything looks good. I've answered the two outstanding convos. Please take a look!

2021-09-02 19:26 UTC, courcelan commented on fetch.js
> +      allPosts.push(...data);
@orlyohreally  Ok, if `allPosts` is already an array, then I think it is more performant to do a `concat`:

```
let appPosts = []
...
allPosts = allPosts.concat(data)
```

doing: `allPosts.push(...data);`

really does: 

```
for (item in data) {
  allPosts.push(item)
}
```

again, this is local/server side, but it they have a ton of posts, it may speed it up for them a bit.

2021-09-02 19:26 UTC, courcelan commented on fetch.js
> +    return collectionsSlugs.reduce(async (resPromise, collectionSlug) => {
when you do `[].map( async () => {} )` you are wrapping it into a `Promise.all` to ensure they are all resolved before getting the response value. I believe `[].reduce( async () => {} )` operates in the same fashion; it should be wrapped in a `Promise.all` too.

2021-09-05 08:07 UTC, orlyohreally commented on fetch.js
> +    return collectionsSlugs.reduce(async (resPromise, collectionSlug) => {
`collectionsSlugs.reduce(...` returns a single promise that resolves an object, not an array of promises, and `Promise.all` is used for an array of promises...

2021-09-05 08:13 UTC, orlyohreally commented on fetch.js
> +      allPosts.push(...data);
Done

2021-09-08 13:58 UTC, courcelan approved these changes
LGTM!

2021-09-09 16:37 UTC, merged

2021-09-09 16:37 UTC, jakelumetta commented
Thanks! Published 2.0 @orlyohreally